---
title: "logFC Assessment for 0 prior edgeR"
author: "Nate Olson"
date: '`r Sys.Date()`'
output:
  bookdown::pdf_document2:
    toc: FALSE
---



```{r logFCsetup, include=FALSE}
library(here)
library(nlme)
library(ape)
library(multcomp)
library(tidyverse)
library(stringr)
library(ggridges)
library(ggpubr)
```

```{r logFCmunge, include = FALSE}
### Loading Data ---------------------------------------------------------------
### RDS file generated in 2017-10-19_logFC-error-metrics.RDS
logFC_pre <- here("data", "logFC_pre_0_prior.RDS") %>% readRDS()

logFC_feature_summary <- here("data","logFC_feature_summary_0_prior.RDS") %>%
      readRDS() %>% 
      mutate(slope_error = abs(1 - slope))

### logFC Est v. Exp Regression ------------------------------------------------
logFCestVexp <- logFC_pre %>%
      filter(T1 != 0, T2 != 20) %>%
      ggplot() +
      # geom_point(aes(x = exp_logFC, y = logFC), alpha = 0.15) +
      geom_smooth(aes(x = exp_logFC, y = logFC, color = pipe), method = "lm") +
      geom_abline(aes(intercept = 0, slope = 1), color = "grey20", linetype = 2) +
      facet_wrap(~biosample_id, ncol = 1, scale = "free_y") + theme_bw()  +
      labs(x = "Expected", y = "Estimate", color = "Pipeline")


### Error Distribution ---------------------------------------------------------
logFC_error <- logFC_pre %>%
      filter(T1 != 0, T2 != 20) %>%
      dplyr::select(biosample_id, pipe, feature_id, exp_logFC, logFC) %>%
      mutate(error = abs(logFC - exp_logFC))

logFC_error_dist <- logFC_error %>%
      ggplot() +
      geom_density_ridges(aes(x = error, y = pipe, color = pipe), alpha = 0.5) +
      facet_wrap(~biosample_id, ncol = 1) + theme_bw() +
      labs(x = "Error", y = "Pipeline", color = "Pipeline")

### logFC Bias: 1-slope  -------------------------------------------------------
slope_logFC <- logFC_feature_summary %>%
      ggplot() +
      geom_boxplot(aes(x = pipe, y = slope_error, color = pipe),
                   outlier.shape = NA) +
      geom_hline(aes(yintercept = 0), color = "grey20", linetype = 2) +
      facet_wrap(~biosample_id, ncol = 1) +
      theme_bw() +
      labs(x = "Pipeline", y = "Bias", color = "Pipeline")

ymin <- ggplot_build(slope_logFC)$data[[1]]$ymin %>% min()
ymax <- ggplot_build(slope_logFC)$data[[1]]$ymax %>% max()
slope_logFC <- slope_logFC + coord_cartesian(ylim = c(ymin, ymax))

### logFC Variance: R2 ---------------------------------------------------------
r2_logFC <- logFC_feature_summary %>%
      # filter(slope < 4) %>%
      ggplot() +
      geom_boxplot(aes(x = pipe, y = adj.r.squared, color = pipe),
                   outlier.shape = NA) +
      geom_hline(aes(yintercept = 1), color = "grey20", linetype = 2) +
      facet_wrap(~biosample_id, ncol = 1) +
      theme_bw() +
      labs(x = "Pipeline", y = "Variance$", color = "Pipeline")


ymin <- ggplot_build(r2_logFC)$data[[1]]$ymin %>% min()
ymax <- ggplot_build(r2_logFC)$data[[1]]$ymax %>% max()
r2_logFC <- r2_logFC + coord_cartesian(ylim = c(ymin, ymax))
```


```{r logFCstats, echo = FALSE, message = FALSE, warning = FALSE}
fit_dat <- logFC_feature_summary %>%
      # filter(slope < 4) %>%
      ungroup() %>% 
      filter(pipe != "unclustered") %>%
      mutate(pipe = factor(pipe))

## Bias - Error rate -----------------------------------------------------------
# Fitting mixed effects model with individual as the fixed effect
slope_fit <- nlme::lme(slope_error ~ pipe, random =  ~ 1 | biosample_id,
                 data = fit_dat)
## Residual check
# qqnorm(slope_fit$residuals) + abline(a = 0, b =  1, col = 'red')

## Slope post-hoc
slope_post_hoc <- glht(slope_fit, linfct = mcp(pipe = "Tukey"), 
                       alternative = "greater")

slope_tukey_p <- summary(slope_post_hoc)$test$pvalues
slope_tukey_t <- summary(slope_post_hoc)$test$tstat

# Pipe 1-slope estimates
dada_slope <- slope_fit$coefficients$fixed['(Intercept)']
mothur_slope <- dada_slope + slope_fit$coefficients$fixed['pipemothur']
qiime_slope <- dada_slope + slope_fit$coefficients$fixed['pipeqiime']

slope_anova <- anova(slope_fit)
slope_f <- slope_anova$`F-value`
slope_p <- slope_anova$`p-value`

# Checking whether indiviudal or pipeline contributes more to the overal vaiance
slope_var <- ape::varcomp(slope_fit)

## Variance - RCOV -------------------------------------------------------------
# Fitting mixed effects model with individual as the fixed effect
r2_fit <- nlme::lme(adj.r.squared ~ pipe, random =  ~ 1 | biosample_id,
                 data = fit_dat)

# qqnorm(r2_fit$residuals) + abline(a = 0, b =  1, col = 'red')

# Pipe R2 estimates
dada_r2 <- r2_fit$coefficients$fixed['(Intercept)']
mothur_r2 <- dada_r2 + r2_fit$coefficients$fixed['pipemothur']
qiime_r2 <- dada_r2 + r2_fit$coefficients$fixed['pipeqiime']

r2_anova <- anova(r2_fit)
r2_f <- r2_anova$`F-value`
r2_p <- r2_anova$`p-value`

# Checking whether indiviudal or pipeline contributes more to the overal vaiance
r2_var <- ape::varcomp(r2_fit)
```

## Stats Results
__BIAS__
```{r}
summary(slope_fit)
```


```{r}
dada_slope
```

```{r}
mothur_slope
```


```{r}
qiime_slope
```

```{r}
slope_var
```

```{r}
slope_anova
```

```{r}
slope_f
```

```{r}
slope_p
```


```{r}
summary(slope_post_hoc)
```

```{r}
confint(slope_post_hoc) %>% 
  broom::tidy() %>% 
  ggplot(aes(lhs, y=estimate, ymin=conf.low, ymax=conf.high)) +
    geom_hline(yintercept=0, linetype="11", colour="grey60") +
    geom_errorbar(width=0.1) + 
    geom_point() +
    coord_flip() +
    theme_classic()
```



```{r}
slope_tukey_p
```

```{r}
slope_tukey_t
```

__Variance__
```{r}
summary(r2_fit)
```

```{r}
dada_r2
```

```{r}
mothur_r2
```


```{r}
qiime_r2
```

```{r}
r2_var
```

```{r}
r2_anova
```

```{r}
r2_f
```

```{r}
r2_p 
```



```{r logFCerror, fig.width = 6.68, fig.cap = "(A) Linear model or the relationship between log fold-change estimates and expected values for PRE-specific and PRE-dominant features by pipeline and individual, line color indicates pipelines. Dashed grey line indicates expected 1-to-1 relationship between the estimated and expected log fold-change. (B) Log fold-change error (|exp-est|) distribution by pipeline and individual.", echo = FALSE, warning=FALSE, message = FALSE}

logFCestVexp <- logFC_pre %>% filter(T1 != 0, T2 != 20) %>%
      mutate(pipe = forcats::fct_recode(pipe,
                                        Unclustered = "unclustered",
                                        DADA2 = "dada2", 
                                        Mothur = "mothur", 
                                        QIIME = "qiime")) %>% 
      ggplot() +
      geom_smooth(aes(x = exp_logFC, y = logFC, color = pipe), method = "lm") +
      geom_abline(aes(intercept = 0, slope = 1), color = "grey20",
                  linetype = 2) +
      facet_wrap( ~ biosample_id, nrow = 1) +
      theme_bw() +
      theme(axis.text.x = element_text(angle = -45, hjust = 0)) + 
      labs(x = "Expected logFC", y = "Estimated logFC", color = "Pipeline")


logFC_error_dist <- logFC_error %>%
      mutate(pipe = forcats::fct_recode(pipe,
                                        Unclustered = "unclustered",
                                        DADA2 = "dada2", 
                                        Mothur = "mothur", 
                                        QIIME = "qiime")) %>% 
      mutate(error = if_else(error < 1e-2, 1e-2, error)) %>%
      ggplot() +
      geom_boxplot(aes(x = biosample_id, y = error, fill = pipe)) +
      theme_bw() +
      labs(y = "|Exp. logFC - Est. logFC|", x = "Individual", fill = "Pipeline") +
      scale_y_log10(breaks = c(0.01, 0.1, 1.0, 10))

ggarrange(logFCestVexp,
          logFC_error_dist,
          labels = "AUTO", align = "v",
          ncol = 1, nrow = 2, common.legend = TRUE, legend = "bottom")
```

```{r echo = FALSE, message = FALSE}
ggsave(here("figs","logFCError0prior.pdf"), width = 170, units = "mm")
```

```{r logFcErrorMetrics, fig.width = 6.68, fig.cap = "Feature-level log-fold change error bias (A) and variance (B) metric distribution by subject and pipeline. The bias ($|1 - slope|$) and variance ($R^2$) metrics are derived from the linear model fit to the estimated and expected log fold-change values for individual features. Boxplot outliers, $1.5\\times IQR$ from the median were excluded from the figure to prevent extreme metric values from obscuring metric value visual comparisons.", echo = FALSE, warning=FALSE, message = FALSE}

slope_logFC <- logFC_feature_summary %>%
      ungroup() %>% 
      mutate(pipe = forcats::fct_recode(pipe,
                                        Unclustered = "unclustered",
                                        DADA2 = "dada2", 
                                        Mothur = "mothur", 
                                        QIIME = "qiime")) %>% 
      ggplot() +

      geom_boxplot(aes(x = biosample_id, y = slope_error, fill = pipe),
                   outlier.shape = NA) +
      geom_hline(aes(yintercept = 0), color = "grey20", linetype = 2) +
      theme_bw() +
      labs(x = "Individual", y = "|1-slope|", fill = "Pipeline")

ymin <- ggplot_build(slope_logFC)$data[[1]]$ymin %>% min()
ymax <- ggplot_build(slope_logFC)$data[[1]]$ymax %>% max()
slope_logFC <- slope_logFC + coord_cartesian(ylim = c(ymin, ymax))


### logFC Variance: R2 ---------------------------------------------------------
r2_logFC <- logFC_feature_summary %>%
      ungroup() %>% 
      mutate(pipe = forcats::fct_recode(pipe,
                                        Unclustered = "unclustered",
                                        DADA2 = "dada2", 
                                        Mothur = "mothur", 
                                        QIIME = "qiime")) %>% 
    ggplot() +
      geom_boxplot(aes(x = biosample_id, y = adj.r.squared, fill = pipe),
                   outlier.shape = NA) +
      geom_hline(aes(yintercept = 1), color = "grey20", linetype = 2) +
      theme_bw() +
      labs(x = "Individual", y = expression(R^2), color = "Pipeline")

ymin <- ggplot_build(r2_logFC)$data[[1]]$ymin %>% min()
ymax <- ggplot_build(r2_logFC)$data[[1]]$ymax %>% max()
r2_logFC <- r2_logFC + coord_cartesian(ylim = c(ymin, ymax))

ggarrange(slope_logFC + rremove("x.text") + rremove("xlab"),
          r2_logFC ,nrow = 2, ncol = 1, heights = c(0.45, 0.55),
          common.legend = TRUE, legend = "bottom",
          align = "v",labels = "AUTO")
```

```{r echo = FALSE, message = FALSE}
ggsave(here("figs", "logFCErrorMetrics0prior.pdf"), width = 170, units = "mm")
```


